adds step to check for enforce admins adds step to disable enforce admin if above check returns true adds step to re-enable enforce admin if check is true

diff --git a/.github/workflows/last-updated.yaml b/.github/workflows/last-updated.yaml
--- a/.github/workflows/last-updated.yaml
+++ b/.github/workflows/last-updated.yaml
@@ -20,18 +20,47 @@ jobs:
         uses: actions/checkout@v3
         with:
           token: ${{secrets.TEMPLATES_GITHUB_TOKEN }}
+
       - name: 'set git config'
         shell: bash
         run: |
           git config --global user.email "action@github.com"
           git config --global user.name "GitHub Action"
+
+      - name: 'check for enforce admins'
+        id: 'check-for-enforce'
+        shell: bash
+        run: |
+          enforceAdmins=$(gh api "/repos/${GITHUB_REPOSITORY}/branches/${DEFAULT_BRANCH}/protection/enforce_admins" --jq '.enabled')
+          echo "::notice is enforce admins enabled? ${enforceAdmins}"
+          echo "enforce_admin=${enforceAdmins}" >> $GITHUB_OUTPUT
+
+      - name: 'disable enforce admins'
+        id: 'disable-force-admins'
+        if: ${{ 'true' == steps.check-for-enforce.outputs.enforce_admin }}
+        shell: bash
+        run: |
+          echo "::notice::Enforce Admins is enabled. Temporarily disabling..."
+          gh api --method DELETE "/repos/${GITHUB_REPOSITORY}/branches/${DEFAULT_BRANCH}/protection/enforce_admins" --quiet \
+               && echo "::notice::Enforce admins disabled" \
+               || echo "::error::Disabling enforce admin failed"
+
       - name: 'update last.updated'
         id: last-updated
         shell: bash
         run: |
-          defaultBranch="${{ github.event.repository.default_branch }}"
           date > ./.platform/last.updated
           git add ./.platform/last.updated
           git commit -m "auto-updates version, post merge"
-          git push origin ${defaultBranch}
+          git push origin "${DEFAULT_BRANCH}"
 
+      - name: "Re-enable enforce admins"
+        id: re-enable-enforce-admin
+        if: ${{ 'true' == steps.check-for-enforce.outputs.enforce_admin }}
+        shell: bash
+        run: |
+          gh api --method POST \
+          -H "Accept: application/vnd.github+json" \
+          "/repos/${GITHUB_REPOSITORY}/branches/${DEFAULT_BRANCH}/protection/enforce_admins" --silent \
+          && echo "::notice::Successfully re-enabled enforce admin" \
+          || echo "::error::Re-enabling enforce admins failed."
